server:
  port: 10000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotoristore_pms?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19926172xz

mybatis-plus:
  mapper-locations: classpath*:/mapper/product/*.xml
  global-config:
    db-config:
      id-type: auto #primary key auto-increment
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志