server:
  port: 8000

spring:
  application:
    name: KotoriStore-member-service
  datasource:
    url: jdbc:mysql://localhost:3306/kotoristore_ums?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19926172xz
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto #primary key auto-increment