server:
  port: 11000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotoristore_wms?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19926172xz

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto #primary key auto-increment